version: '3'

services:
  database:
    image: 'postgres:latest'
    environment: 
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB} 
    ports:
      - '15432:5432'
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./postgres:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks: 
  postgres-network:
    driver: bridge